openapi: 3.0.0
info:
  version: "2.0"
  title: IVMS101 sample output of Sygna Bridge
paths:
  /ivms/example1:
      post:
        description: 'VASP A, on behalf of originator Alice Smith, transfers 1BTC to Bob Barnes, who holds a custodial wallet with VASP B.'
        summary: 'Example 1'
        tags:
          - IVMS
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ivms101.Example1'
          required: true
        responses:
          '200':
              description: ''
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ivms101.Status'
                  examples:
                    response:
                      value:
                        status: OK
  /ivms/example2:
    post:
      description: 'VASP C, on behalf of originator 吴信利 (Xinli Wu), transfers 1 ETH to ABC Limited (trading as CBA Trading), which holds a custodial wallet with VASP D. VASP C routes ETH transfers through the intermediary VASP E.'
      summary: 'Example 2'
      tags:
        - IVMS
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ivms101.Example2'
        required: true
      responses:
        '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ivms101.Status'
                examples:
                  response:
                    value:
                      status: OK
components:
  schemas:
    ivms101.Example1:
      title: Example1
      example:
        originator:
          originator_persons:
          - natural_person:
              name:
                name_identifiers:
                - primary_identifier: Smith
                  secondary_identifier: Dr Alice
                  name_identifier_type: LEGL
                phonetic_name_identifiers: []
              geographic_addresses: 
                - 
                  address_type: GEOG
                  department: ''
                  sub_department: ''
                  street_name: Potential Street
                  building_number: '24'
                  building_name: Weathering Views
                  floor: ''
                  post_box: ''
                  room: ''
                  post_code: '91765'
                  town_name: Walnut
                  town_location_name: ''
                  district_name: ''
                  country_sub_division: California
                  address_line: []
                  country: US
              national_identification:
                name_identifiers: '446005'
                national_identifier_type: RAID
                country_of_issue: ''
                registration_authority: RA000553
              customer_identification: '1002390'
              date_and_place_of_birth: 
                date_of_birth: ''
                place_of_birth: ''
              country_of_residence: ''
          account_numbers:
          - '10023909'
        beneficiary:
          beneficiary_persons:
          - natural_person:
              name:
                name_identifiers:
                - primary_identifier: Barnes
                  secondary_identifier: Robert
                  name_identifier_type: LEGL
                phonetic_name_identifiers: []
              geographic_addresses: []
              customer_number: ''
              country_of_registration: ''
          account_numbers:
          - 1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2
        originating_vasp:
          originating_vasp:
          - legal_person:
              name:
                name_identifiers:
                - legal_person_name: VASP A
                  legal_person_name_identifier_type: LEGL
                local_name_identifiers: []
                phonetic_name_identifiers: []
              geographic_addresses: []
              national_identification:
                name_identifiers: '3M5E1GQKGL17HI8CPN20'
                national_identifier_type: LEIX
                country_of_issue: ''
                registration_authority: ''
              customer_number: ''
              country_of_registration: ''
      properties:
        originator:
          $ref: '#/components/schemas/ivms101.Originator'
        beneficiary:
          $ref: '#/components/schemas/ivms101.Beneficiary'
        originating_vasp:
          $ref: '#/components/schemas/ivms101.OriginatingVasp'
    ivms101.Example2:
      title: Example2
      example:
        originator:
          originator_persons:
          - natural_person:
              name:
                name_identifiers:
                - primary_identifier: Wu
                  secondary_identifier: Xinli
                  name_identifier_type: LEGL
                local_name_identifiers:
                - primary_identifier: 吳
                  secondary_identifier: 信利
                  name_identifier_type: LEGL
                phonetic_name_identifiers: []
              geographic_addresses: []
              national_identification:
                name_identifiers: '446005'
                national_identifier_type: RAID
                country_of_issue: ''
                registration_authority: RA000553
              customer_identification: ''
              date_and_place_of_birth: 
                date_of_birth: ''
                place_of_birth: ''
              country_of_residence: TZ
          account_numbers:
          - 1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2
        beneficiary:
          beneficiary_persons:
          - legal_person:
              name:
                name_identifiers:
                - legal_person_name: ABC Limited
                  legal_person_name_identifier_type: LEGL
                local_name_identifiers: []
                phonetic_name_identifiers: []
              geographic_addresses: []
              customer_number: ''
              country_of_registration: ''
          - legal_person:
              name:
                name_identifiers:
                - legal_person_name: CBA Trading
                  legal_person_name_identifier_type: LEGL
                local_name_identifiers: []
                phonetic_name_identifiers: []
              geographic_addresses: []
              customer_number: ''
              country_of_registration: ''
          account_numbers:
          - 00010190CBATRAD
        payload_metadata:
          transliteration_method:
          - hani
        transfer_path: 
        - intermediary_vasp:
            legal_person:
              name:
                name_identifiers:
                - legal_person_name: VASP E
                  legal_person_name_identifier_type: LEGL
          sequence: 0
      properties:
        originator:
          $ref: '#/components/schemas/ivms101.Originator'
        beneficiary:
          $ref: '#/components/schemas/ivms101.Beneficiary'
        payload_metadata:
          $ref: '#/components/schemas/ivms101.PayloadMetadata'
        transfer_path:
          $ref: '#/components/schemas/ivms101.TransferPath'
    ivms101.NaturalPersonNameId:
      title: NaturalPersonNameId
      example:
        primary_identifier: 'Wu'
        secondary_identifier: 'Xinli'
        name_identifier_type: 'LEGL'
      type: object
      properties:
        primary_identifier:
          type: string
        secondary_identifier:
          type: string
        name_identifier_type:
          title: NaturalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.NaturalPersonNameTypeCode"
    ivms101.LocalNaturalPersonNameId:
      title: LocalNaturalPersonNameId
      example:
        primary_identifier: '吳'
        secondary_identifier: '信利'
        name_identifier_type: 'LEGL'
      type: object
      properties:
        primary_identifier:
          type: string
        secondary_identifier:
          type: string
        name_identifier_type:
          title: NaturalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.NaturalPersonNameTypeCode"
    ivms101.LocalLegalPersonNameId:
      title: LocalLegalPersonNameId
      example:
        legal_person_name: 'ABC Limited'
        legal_person_name_identifier_type: 'LEGL'
      type: object
      properties:
        legal_person_name:
          type: string
        legal_person_name_identifier_type:
          title: LegalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.LegalPersonNameTypeCode"
    ivms101.Address:
      title: Address
      example:
        address_type: 'GEOG'
        street_name: 'Potential Street'
        building_number: '24'
        building_name: 'Weathering Views'
        post_code: '91765'
        town_name: 'Walnut'
        countrySubDivision: 'California'
        country: 'US'
      type: object
      properties:
        address_type:
          title: AddressTypeCode
          type: string
          items:
             $ref: "#/components/schemas/ivms101.AddressTypeCode"
        department:
          type: string
        sub_department:
          type: string
        street_name:
          type: string
        building_number:
          type: string
        building_name:
          type: string
        floor:
          type: string
        post_box:
          type: string
        room:
          type: string
        post_code:
          type: string
        town_name:
          type: string
        town_location_name:
          type: string
        district_name:
          type: string
        country_sub_division:
          type: string
        address_line:
          type: array
          items:
            type: string
        country:
          type: string
    ivms101.NationalIdentification:
      title: NationalIdentification
      example:
        national_identifier: '446005'
        national_identifier_type: 'RAID'
        registration_authority: 'RA000553'
      type: object
      properties:
        national_identifier:
          type: string
          description: An identifier issued by an appropriate issuing authority
        national_identifier_type:
          title: NationalIdentifierTypeCode
          type: string
          items:
            $ref: '#/components/schemas/ivms101.NationalIdentifierTypeCode'
        country_of_issue:
          type: string
          description: Country of the issuing authority
        registration_authority:
          type: string
          description: A code specifying the registration authority
          # above are belong to type defination
    ivms101.Person:
      title: Person
      type: object
      properties:
        natural_person:
          $ref: "#/components/schemas/ivms101.NaturalPerson"
        legal_person:
          $ref: "#/components/schemas/ivms101.LegalPerson"
    ivms101.NaturalPerson:
      title: NaturalPerson
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ivms101.NaturalPersonName"
        geographic_addresses:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Address"
        national_identification:
          $ref: "#/components/schemas/ivms101.NationalIdentification"
        customer_identification:
          type: string
        date_and_place_of_birth:
          $ref: "#/components/schemas/ivms101.DateAndPlaceOfBirth"
        country_of_residence:
          type: string
      required: 
        - name
    ivms101.NaturalPersonName:
      title: NaturalPersonName
      example:
        primary_identifier: 'Wu'
        secondary_identifier: 'Xinli'
        name_identifier_type: 'LEGL'
      type: object
      properties:
        name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.NaturalPersonNameId"
        local_name_identifiers:
          description: full name separated into primary and secondary identifier using local characters
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalNaturalPersonNameId"
        phonetic_name_identifiers:
          description: Alternate representation of a name that corresponds to the manner the name is pronounced
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalNaturalPersonNameId"
      required: 
        - name_identifiers
    ivms101.DateAndPlaceOfBirth:
      title: DateAndPlaceOfBirth
      description: 'If dateOfBirth is specified, the date specified must be a historic date (i.e. a date prior to the current date)'
      type: object
      properties:
        date_of_birth:
          description: 'Date on which a person is born.'
          type: string
        place_of_birth:
          description: 'The town and/or the city and/or the suburb and/or the country subdivision and/or the country where the person was born.'
          type: string
    ivms101.LegalPerson:
      title: LegalPerson
      type: object
      properties:
        name:
          $ref: "#/components/schemas/ivms101.LegalPersonName"
        geographic_addresses:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Address"
        customer_number:
          type: string
        national_identification:
          $ref: "#/components/schemas/ivms101.NationalIdentification"
        country_of_registration:
          type: string
      required: 
        - name
    ivms101.LegalPersonName:
      title: LegalPersonName
      type: object
      properties:
        name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LegalPersonNameId"
        local_name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalLegalPersonNameId"
        phonetic_name_identifiers:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.LocalLegalPersonNameId"
      required: 
        - name_identifiers
    ivms101.LegalPersonNameId:
      title: LegalPersonNameId
      example:
        legal_person_name: 'CBA Trading'
        legal_person_name_identifier_type: 'TRAD'
      type: object
      properties:
        legal_person_name:
          type: string
        legal_person_name_identifier_type:
          title: LegalPersonNameTypeCode
          type: string
          items:
            $ref: "#/components/schemas/ivms101.LegalPersonNameTypeCode"
    ivms101.IntermediaryVasp:
      title: IntermediaryVasp
      type: object
      properties:
        intermediary_vasp:
          $ref: "#/components/schemas/ivms101.Person"
        sequence:
          type: integer
          minimum: 0
          maximum: 9007199254740991
    ivms101.Originator:
      title: Originator
      type: object
      properties:
        originator_persons:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Person"
        account_numbers:
          type: array
          items:
            type: string
    ivms101.Beneficiary:
      title: Beneficiary
      type: object
      properties:
        beneficiary_persons:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.Person"
        account_numbers:
          type: array
          items:
            type: string
    ivms101.OriginatingVasp:
      title: OriginatingVasp
      description:  The VASP which initiates the VA transfer, and transfers the VA upon receiving the request for a VA transfer on behalf of the originator
      type: object
      properties:
        originating_vasp:
          $ref: "#/components/schemas/ivms101.Person"
    ivms101.BeneficiaryVasp:
      title: BeneficiaryVasp
      description: The VASP which receives the transfer of a virtual asset from the originating VASP directly or through an intermediary VASP and makes the funds available to the beneficiary
      type: object
      properties:
        beneficiary_vasp:
          $ref: "#/components/schemas/ivms101.Person"
    ivms101.TransferPath:
      title: TransferPath
      type: object
      properties:
        transfer_path:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.IntermediaryVasp"
    ivms101.PayloadMetadata:
      title: PayloadMetadata
      example:
        transliteration_method: 'HANI'
      type: object
      properties:
        transliteration_method:
          type: array
          items:
            $ref: "#/components/schemas/ivms101.TransliterationMethodCode"
    ivms101.IdentityPayload:
      title: IdentityPayload
      type: object
      properties:
        originator:
          $ref: "#/components/schemas/ivms101.Originator"
        beneficiary:
          $ref: "#/components/schemas/ivms101.Beneficiary"
        originating_vasp:
          $ref: "#/components/schemas/ivms101.OriginatingVasp"
        beneficiary_vasp:
          $ref: "#/components/schemas/ivms101.BeneficiaryVasp"
        transfer_path:
          $ref: "#/components/schemas/ivms101.TransferPath"
        payload_metadata:
          $ref: "#/components/schemas/ivms101.PayloadMetadata"
    ivms101.NaturalPersonNameTypeCode:
      title: NaturalPersonNameTypeCode
      description: Identifies the nature of the name being specified for a natural person ([IVMS Ref. NaturalPersonNameTypeCode](https://intervasp.org/)).>

              * `ALIA` - Alias name, A name other than the legal name by which a natural person is also known

              * `BIRT` - Name at birth, The name given to a natural person at birth

              * `MAID` - Maiden name, The original name of a natural person who has changed their name after marriage

              * `LEGL` - Legal name, The name that identifies a natural person for legal, official or administrative purposes

              * `MISC` - Unspecified, A name by which a natural person may be known but cannot otherwise be categorized
      type: string
      enum:
#        - ALIA
        - ALIA
        - BIRT
        - MAID
        - LEGL
        - MISC
    ivms101.LegalPersonNameTypeCode:
      title: LegalPersonNameTypeCode
      description: A single value corresponding to the nature of name being specified for the legal person>

           * `LEGL` - Legal name, Official name under which an organisation is registered

           * `SHRT` - Short name, Specifies the short name of the organisation

           * `TRAD` - Trading name, Name used by a business for commercial purposes, although its registered legal name, used for contracts and other formal situations, may be another
      type: string
      enum:
#        - LEGL
        - LEGL
        - SHRT
        - TRAD
    ivms101.AddressTypeCode:
      title: AddressTypeCode
      description: ([IVMS Ref. AddressTypeCode](https://intervasp.org/))>

              * `HOME` - Residential, Address is the home address

              * `BIZZ` - Business, Address is the business address

              * `GEOG` - Geographic, Address is the unspecified physical (geographical) address suitable for identification of the natural or legal person
      type: string
      enum:
#        - HOME
        - HOME
        - BIZZ
        - GEOG
    ivms101.NationalIdentifierTypeCode:
      title: NationalIdentifierTypeCode
      description: Specifies the type of identifier specified.>

            * `ARNU` - Alien registration number, Number assigned by a government agency to identify foreign nationals.

            * `CCPT` - Passport number, Number assigned by a passport authority.

            * `RAID` - Registration authority identifier, Identifier of a legal entity as maintained by a registration authority.

            * `DRLC` - Driver license number, Number assigned to a driver's license

            * `FIIN` - Foreign investment identity number, Number assigned to a foreign investor number (other than the alien number)

            * `TXID` - Tax identification number, Number assigned by a tax authority to an entity

            * `SOCS` - Social security number, Number assigned by a social security agency

            * `IDCD` - Identity card number, Number assigned by a national authority to an identity card

            * `LEIX` - Legal Entity Identifier, Legal Entity Identifier (LEI) assigned in accordance with ISO 1744211

            * `MISC` - Unspecified, A national identifier which may be known but which cannot otherwise be categorized or the category of which the sender is unable to determine.
      type: string
      enum:
        # - ARNU
        - ARNU
        - CCPT
        - RAID
        - DRLC
        - FIIN
        - TXID
        - SOCS
        - IDCD
        - LEIX
        - MISC
    ivms101.TransliterationMethodCode:
      title: TransliterationMethodCode
      description:  Identifies the national script from which transliteration to Latin script is applied.>

            * `arab` - Arabic (Arabic language), ISO233-2:1993

            * `aran` - Arabic (Persian language), ISO 233-3:1999

            * `armn` - Armenian, ISO 9985:1996

            * `cyrl` - Cyrillic, ISO 9:1995

            * `deva` - Devanagari & related Indic, ISO 15919:2001

            * `geor` - Devanagari & related Indic, ISO 9984:1996

            * `grek` - Greek, ISO 843:1997

            * `hani` - Han (Hanzi, Kanji, Hanja), ISO 7098:2015

            * `hebr` - Hebrew, ISO 259-2:1994

            * `kana` - Kana, ISO 3602:1989

            * `kore` - Korean, Revised Romanization of Korean

            * `thai` - Thai, ISO 11940-2:2007

            * `thai` - Script other than those listed above, Unspecified
      type: string
      enum:
#        - ARAB
        - ARAB
        - ARAN
        - ARMN
        - CYRL
        - DEVA
        - GEOR
        - GREK
        - HANI
        - HEBR
        - KANA
        - KORE
        - THAI
        - OTHR
    ivms101.Status:
      title: Status
      example:
        status: OK
      type: object
      properties:
        status:
          type: string
      required:
        - status
